In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd

import mysql.connector

from sqlalchemy import create_engine

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
df = pd.read_csv("../data/cleaned/ola_cleaned.csv")

print(df.shape)

df.head()

(100000, 36)

,Booking ID,Booking Date,Booking Time,City,Customer ID,Driver ID,Vehicle Type,Pickup Location,Drop Location,Booking Status,...,Year,Weekday,Quarter,Peak Hour,Time Of Day,Fare Per KM,Booking Category,Distance Category,Driver Rating Category,Customer Rating Category
0,OLA000001,2024-03-25,16:38:00,Pune,C26989,D7632,Sedan,MG Road,Koramangala,Success,...,2024,Monday,1,Normal,Afternoon,20.70,Low,Long,Excellent,Good
1,OLA000002,2024-04-01,14:52:00,Pune,C35331,D6588,Prime Sedan,Electronic City,Yelahanka,Success,...,2024,Monday,2,Normal,Afternoon,22.88,Low,Long,Excellent,Excellent
2,OLA000003,2024-09-11,01:18:00,Mumbai,C18767,D1455,Sedan,Whitefield,Electronic City,Success,...,2024,Wednesday,3,Normal,Night,44.13,Low,Short,Excellent,Excellent
3,OLA000004,2024-06-28,23:38:00,Hyderabad,C21721,D1529,Prime SUV,Koramangala,Hebbal,Success,...,2024,Friday,2,Normal,Night,27.96,Low,Medium,Average,Average
4,OLA000005,2024-03-17,13:48:00,Hyderabad,C53922,D9618,Auto,Indiranagar,Whitefield,Success,...,2024,Sunday,1,Normal,Afternoon,24.45,Low,Short,Excellent,Excellent

In [11]:
HOST = "127.0.0.1"

USER = "root"

PASSWORD = "Surya@123"

DATABASE = "ola_analytics"

In [12]:
connection = mysql.connector.connect(

host=HOST,

user=USER,

password=PASSWORD

)

cursor = connection.cursor()

print("Connected Successfully")

Connected Successfully

In [13]:
cursor.execute(

f"""

CREATE DATABASE IF NOT EXISTS {DATABASE};

"""

)

print("Database Created")

Database Created

In [14]:
cursor.execute(

f"USE {DATABASE}"

)

print("Database Selected")

Database Selected

In [15]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

connection_url = URL.create(
    drivername="mysql+mysqlconnector",
    username=USER,
    password=PASSWORD,
    host=HOST,
    database=DATABASE
)

engine = create_engine(connection_url)

print("Engine Created Successfully")

Engine Created Successfully

In [16]:
df.to_sql(

"ola_rides",

engine,

if_exists="replace",

index=False

)

print("Data Imported Successfully")

Data Imported Successfully

In [17]:
query="""

SELECT COUNT(*)

FROM ola_rides;

"""

count=pd.read_sql(query,engine)

count

   COUNT(*)
0    100000

In [18]:
query="""

SELECT *

FROM ola_rides

LIMIT 10;

"""

sample=pd.read_sql(query,engine)

sample

,Booking ID,Booking Date,Booking Time,City,Customer ID,Driver ID,Vehicle Type,Pickup Location,Drop Location,Booking Status,...,Year,Weekday,Quarter,Peak Hour,Time Of Day,Fare Per KM,Booking Category,Distance Category,Driver Rating Category,Customer Rating Category
0,OLA000001,2024-03-25,16:38:00,Pune,C26989,D7632,Sedan,MG Road,Koramangala,Success,...,2024,Monday,1,Normal,Afternoon,20.70,Low,Long,Excellent,Good
1,OLA000002,2024-04-01,14:52:00,Pune,C35331,D6588,Prime Sedan,Electronic City,Yelahanka,Success,...,2024,Monday,2,Normal,Afternoon,22.88,Low,Long,Excellent,Excellent
2,OLA000003,2024-09-11,01:18:00,Mumbai,C18767,D1455,Sedan,Whitefield,Electronic City,Success,...,2024,Wednesday,3,Normal,Night,44.13,Low,Short,Excellent,Excellent
3,OLA000004,2024-06-28,23:38:00,Hyderabad,C21721,D1529,Prime SUV,Koramangala,Hebbal,Success,...,2024,Friday,2,Normal,Night,27.96,Low,Medium,Average,Average
4,OLA000005,2024-03-17,13:48:00,Hyderabad,C53922,D9618,Auto,Indiranagar,Whitefield,Success,...,2024,Sunday,1,Normal,Afternoon,24.45,Low,Short,Excellent,Excellent
5,OLA000006,2024-02-08,02:46:00,Chennai,C74154,D7140,Bike,Electronic City,Marathahalli,Success,...,2024,Thursday,1,Normal,Night,18.09,Low,Short,Good,Average
6,OLA000007,2024-04-05,08:57:00,Chennai,C64249,D1617,Auto,HSR Layout,Koramangala,Success,...,2024,Friday,2,Morning Peak,Morning,20.96,Low,Short,Good,Good
7,OLA000008,2024-12-28,02:30:00,Mumbai,C18244,D2827,Auto,Airport,Koramangala,Success,...,2024,Saturday,4,Normal,Night,16.78,Low,Medium,Excellent,Good
8,OLA000009,2024-03-01,18:18:00,Pune,C50670,D3460,Mini,MG Road,Indiranagar,Success,...,2024,Friday,1,Evening Peak,Evening,24.49,Medium,Long,Excellent,Excellent
9,OLA000010,2024-05-01,16:03:00,Hyderabad,C99556,D5262,Prime SUV,Koramangala,Yelahanka,Success,...,2024,Wednesday,2,Normal,Afternoon,38.32,Low,Short,Good,Good

In [19]:
query="""

SHOW COLUMNS

FROM ola_rides;

"""

columns=pd.read_sql(query,engine)

columns

                           Field    Type Null Key Default Extra
0                     Booking ID    text  YES        None
1                   Booking Date    text  YES        None
2                   Booking Time    text  YES        None
3                           City    text  YES        None
4                    Customer ID    text  YES        None
5                      Driver ID    text  YES        None
6                   Vehicle Type    text  YES        None
7                Pickup Location    text  YES        None
8                  Drop Location    text  YES        None
9                 Booking Status    text  YES        None
10            Ride Distance (km)  double  YES        None
11           Ride Duration (min)  bigint  YES        None
12                 Booking Value  double  YES        None
13              Surge Multiplier  double  YES        None
14                      Discount  bigint  YES        None
15                Payment Method    text  YES        None
16                       Weather    text  YES        None
17                       Traffic    text  YES        None
18                 Driver Rating  double  YES        None
19               Customer Rating  double  YES        None
20  Cancelled by Customer Reason    text  YES        None
21    Cancelled by Driver Reason    text  YES        None
22                       Weekend    text  YES        None
23                          Hour  bigint  YES        None
24                           Day  bigint  YES        None
25                         Month    text  YES        None
26                          Year  bigint  YES        None
27                       Weekday    text  YES        None
28                       Quarter  bigint  YES        None
29                     Peak Hour    text  YES        None
30                   Time Of Day    text  YES        None
31                   Fare Per KM  double  YES        None
32              Booking Category    text  YES        None
33             Distance Category    text  YES        None
34        Driver Rating Category    text  YES        None
35      Customer Rating Category    text  YES        None

In [20]:
query="""

SELECT

COUNT(DISTINCT `Customer ID`)

AS Customers

FROM ola_rides;

"""

pd.read_sql(query,engine)

   Customers
0      60599

In [21]:
query="""

SELECT

COUNT(DISTINCT `Driver ID`)

AS Drivers

FROM ola_rides;

"""

pd.read_sql(query,engine)

   Drivers
0     9000

In [22]:
query="""

SELECT

SUM(`Booking Value`)

AS Revenue

FROM ola_rides;

"""

pd.read_sql(query,engine)

       Revenue
0  18627666.96

In [23]:
query="""

SELECT

AVG(`Booking Value`)

AS AverageFare

FROM ola_rides;

"""

pd.read_sql(query,engine)

   AverageFare
0    186.27667

In [24]:
query="""

SELECT

AVG(`Ride Distance (km)`)

AS AverageDistance

FROM ola_rides;

"""

pd.read_sql(query,engine)

   AverageDistance
0         8.808472

In [25]:
query="""

SELECT

COUNT(*)

FROM ola_rides

WHERE

`Booking Status`='Success';

"""

pd.read_sql(query,engine)

   COUNT(*)
0     80139

In [26]:
query="""

SELECT

COUNT(*)

FROM ola_rides

WHERE

`Booking Status`!='Success';

"""

pd.read_sql(query,engine)

   COUNT(*)
0     19861

In [27]:
connection.close()

print("Connection Closed")

Connection Closed