In [4]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd

from sqlalchemy import create_engine
from sqlalchemy.engine import URL

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [5]:
HOST = "127.0.0.1"
USER = "root"
PASSWORD = "Surya@123"
DATABASE = "ola_analytics"

In [6]:
connection_url = URL.create(
    drivername="mysql+mysqlconnector",
    username=USER,
    password=PASSWORD,
    host=HOST,
    database=DATABASE
)

engine = create_engine(connection_url)

print("Connected Successfully")

Connected Successfully

In [7]:
query = """
SELECT COUNT(*) AS Total_Rides
FROM ola_rides;
"""

pd.read_sql(query, engine)

   Total_Rides
0       100000

In [8]:
query = """
SELECT
ROUND(SUM(`Booking Value`),2) AS Total_Revenue
FROM ola_rides;
"""

pd.read_sql(query, engine)

   Total_Revenue
0    18627666.96

In [9]:
query = """
SELECT
ROUND(AVG(`Booking Value`),2) AS Average_Fare
FROM ola_rides;
"""

pd.read_sql(query, engine)

   Average_Fare
0        186.28

In [10]:
query = """
SELECT
ROUND(AVG(`Ride Distance (km)`),2) AS Average_Distance
FROM ola_rides;
"""

pd.read_sql(query, engine)

   Average_Distance
0              8.81

In [11]:
query = """
SELECT COUNT(*) AS Successful_Rides
FROM ola_rides
WHERE `Booking Status`='Success';
"""

pd.read_sql(query, engine)

   Successful_Rides
0             80139

In [12]:
query = """
SELECT COUNT(*) AS Cancelled_Rides
FROM ola_rides
WHERE `Booking Status`<>'Success';
"""

pd.read_sql(query, engine)

   Cancelled_Rides
0            19861

In [13]:
query = """
SELECT
City,
ROUND(SUM(`Booking Value`),2) AS Revenue
FROM ola_rides
GROUP BY City
ORDER BY Revenue DESC;
"""

pd.read_sql(query, engine)

        City     Revenue
0    Chennai  3140012.03
1  Hyderabad  3126540.19
2       Pune  3108372.14
3  Bengaluru  3097141.93
4     Mumbai  3085263.91
5      Delhi  3070336.76

In [14]:
query = """
SELECT
`Vehicle Type`,
ROUND(SUM(`Booking Value`),2) AS Revenue
FROM ola_rides
GROUP BY `Vehicle Type`
ORDER BY Revenue DESC;
"""

pd.read_sql(query, engine)

  Vehicle Type     Revenue
0        Sedan  3577981.26
1  Prime Sedan  3396870.80
2    Prime SUV  3084818.95
3         Mini  3006392.44
4         Bike  2818141.44
5         Auto  2743462.07

In [15]:
query = """
SELECT
`Vehicle Type`,
ROUND(AVG(`Booking Value`),2) AS Average_Fare
FROM ola_rides
GROUP BY `Vehicle Type`
ORDER BY Average_Fare DESC;
"""

pd.read_sql(query, engine)

  Vehicle Type  Average_Fare
0    Prime SUV        258.45
1  Prime Sedan        226.96
2        Sedan        197.96
3         Mini        176.37
4         Auto        154.15
5         Bike        139.65

In [16]:
query = """
SELECT
City,
COUNT(*) AS Ride_Count
FROM ola_rides
GROUP BY City
ORDER BY Ride_Count DESC;
"""

pd.read_sql(query, engine)

        City  Ride_Count
0    Chennai       16780
1  Hyderabad       16771
2       Pune       16648
3     Mumbai       16637
4      Delhi       16597
5  Bengaluru       16567

In [17]:
query = """
SELECT
`Payment Method`,
COUNT(*) AS Total_Rides,
ROUND(SUM(`Booking Value`),2) AS Revenue
FROM ola_rides
GROUP BY `Payment Method`
ORDER BY Revenue DESC;
"""

pd.read_sql(query, engine)

  Payment Method  Total_Rides     Revenue
0            UPI        49979  9297054.57
1           Cash        19972  3738764.50
2           Card        19904  3702102.58
3         Wallet        10145  1889745.31

In [18]:
query = """
SELECT
`Booking Status`,
COUNT(*) AS Total
FROM ola_rides
GROUP BY `Booking Status`;
"""

pd.read_sql(query, engine)

          Booking Status  Total
0                Success  80139
1  Cancelled by Customer   7938
2        No Driver Found   2934
3    Cancelled by Driver   6004
4             Incomplete   2985

In [19]:
query = """
SELECT
`Pickup Location`,
COUNT(*) AS Total_Rides
FROM ola_rides
GROUP BY `Pickup Location`
ORDER BY Total_Rides DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

   Pickup Location  Total_Rides
0          MG Road        10140
1      Indiranagar        10139
2  Electronic City        10130
3           Hebbal        10098
4          Airport        10086
5       Whitefield         9962
6      Koramangala         9927
7        Yelahanka         9874
8       HSR Layout         9843
9     Marathahalli         9801

In [20]:
query = """
SELECT
`Drop Location`,
COUNT(*) AS Total_Rides
FROM ola_rides
GROUP BY `Drop Location`
ORDER BY Total_Rides DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

     Drop Location  Total_Rides
0       HSR Layout        10118
1        Yelahanka        10100
2           Hebbal        10040
3      Koramangala        10031
4          MG Road        10010
5     Marathahalli         9992
6       Whitefield         9964
7          Airport         9938
8  Electronic City         9921
9      Indiranagar         9886

In [21]:
query = """
SELECT
`Customer ID`,
COUNT(*) AS Total_Rides
FROM ola_rides
GROUP BY `Customer ID`
ORDER BY Total_Rides DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

  Customer ID  Total_Rides
0      C82572            7
1      C84704            7
2      C31763            7
3      C48122            7
4      C39937            7
5      C43114            7
6      C17491            7
7      C82381            7
8      C48044            7
9      C57594            7

In [22]:
query = """
SELECT
`Driver ID`,
COUNT(*) AS Total_Rides
FROM ola_rides
GROUP BY `Driver ID`
ORDER BY Total_Rides DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

  Driver ID  Total_Rides
0     D1810           26
1     D5834           24
2     D9178           24
3     D8097           23
4     D8245           23
5     D1486           23
6     D7696           23
7     D9947           23
8     D8568           23
9     D9001           22

In [23]:
query = """
SELECT
ROUND(AVG(`Driver Rating`),2) AS Avg_Driver_Rating
FROM ola_rides;
"""

pd.read_sql(query, engine)

   Avg_Driver_Rating
0                4.5

In [24]:
query = """
SELECT
ROUND(AVG(`Customer Rating`),2) AS Avg_Customer_Rating
FROM ola_rides;
"""

pd.read_sql(query, engine)

   Avg_Customer_Rating
0                  4.4

In [25]:
query = """
SELECT
Weather,
COUNT(*) AS Total_Rides,
ROUND(AVG(`Booking Value`),2) AS Avg_Fare
FROM ola_rides
GROUP BY Weather;
"""

pd.read_sql(query, engine)

  Weather  Total_Rides  Avg_Fare
0   Rainy        19753    185.56
1  Cloudy        19978    186.46
2   Sunny        55226    186.39
3     Fog         5043    187.17

In [26]:
query = """
SELECT
Traffic,
ROUND(AVG(`Ride Duration (min)`),2) AS Avg_Duration
FROM ola_rides
GROUP BY Traffic;
"""

pd.read_sql(query, engine)

  Traffic  Avg_Duration
0    High         47.89
1     Low         47.56
2  Medium         48.12

In [27]:
print("="*60)
print("SQL BUSINESS ANALYSIS COMPLETED")
print("="*60)

============================================================
SQL BUSINESS ANALYSIS COMPLETED
============================================================

In [28]:
query = """
SELECT
    Month,
    ROUND(SUM(`Booking Value`),2) AS Revenue
FROM ola_rides
GROUP BY Month
ORDER BY MIN(`Booking Date`);
"""

pd.read_sql(query, engine)

        Month     Revenue
0     January  1578180.66
1    February  1502380.20
2       March  1589807.44
3       April  1529569.00
4         May  1582444.98
5        June  1538258.50
6        July  1589600.09
7      August  1592412.49
8   September  1492660.20
9     October  1567809.95
10   November  1536476.98
11   December  1528066.47

In [29]:
query = """
SELECT
    Weekday,
    ROUND(SUM(`Booking Value`),2) AS Revenue
FROM ola_rides
GROUP BY Weekday;
"""

pd.read_sql(query, engine)

     Weekday     Revenue
0     Monday  2667116.99
1  Wednesday  2668012.06
2     Friday  2702356.09
3     Sunday  2635507.20
4   Thursday  2670876.42
5   Saturday  2630969.56
6    Tuesday  2652828.64

In [30]:
query = """
SELECT
    `Peak Hour`,
    COUNT(*) AS Total_Rides,
    ROUND(SUM(`Booking Value`),2) AS Revenue
FROM ola_rides
GROUP BY `Peak Hour`;
"""

pd.read_sql(query, engine)

      Peak Hour  Total_Rides      Revenue
0        Normal        62673  11316714.83
1  Morning Peak        16427   3187847.16
2  Evening Peak        20900   4123104.97

In [31]:
query = """
SELECT
    `Time Of Day`,
    COUNT(*) AS Total_Rides,
    ROUND(AVG(`Booking Value`),2) AS Avg_Fare
FROM ola_rides
GROUP BY `Time Of Day`;
"""

pd.read_sql(query, engine)

  Time Of Day  Total_Rides  Avg_Fare
0   Afternoon        20918    180.06
1       Night        33529    181.89
2     Morning        28888    187.24
3     Evening        16665    201.25

In [32]:
query = """
SELECT
    Weekend,
    COUNT(*) AS Total_Rides,
    ROUND(SUM(`Booking Value`),2) AS Revenue
FROM ola_rides
GROUP BY Weekend;
"""

pd.read_sql(query, engine)

  Weekend  Total_Rides      Revenue
0      No        71636  13361190.20
1     Yes        28364   5266476.76

In [33]:
query = """
SELECT
    ROUND(AVG(`Fare Per KM`),2) AS Avg_Fare_Per_KM
FROM ola_rides;
"""

pd.read_sql(query, engine)

   Avg_Fare_Per_KM
0            25.29

In [34]:
query = """
SELECT
    `Vehicle Type`,
    SUM(`Booking Value`) AS Revenue,
    RANK() OVER(
        ORDER BY SUM(`Booking Value`) DESC
    ) AS Vehicle_Rank
FROM ola_rides
GROUP BY `Vehicle Type`;
"""

pd.read_sql(query, engine)

  Vehicle Type     Revenue  Vehicle_Rank
0        Sedan  3577981.26             1
1  Prime Sedan  3396870.80             2
2    Prime SUV  3084818.95             3
3         Mini  3006392.44             4
4         Bike  2818141.44             5
5         Auto  2743462.07             6

In [35]:
query = """
SELECT
    City,
    SUM(`Booking Value`) AS Revenue
FROM ola_rides
GROUP BY City
ORDER BY Revenue DESC
LIMIT 5;
"""

pd.read_sql(query, engine)

        City     Revenue
0    Chennai  3140012.03
1  Hyderabad  3126540.19
2       Pune  3108372.14
3  Bengaluru  3097141.93
4     Mumbai  3085263.91

In [36]:
query = """
SELECT
    City,
    ROUND(AVG(`Customer Rating`),2) AS Avg_Rating
FROM ola_rides
GROUP BY City
ORDER BY Avg_Rating DESC;
"""

pd.read_sql(query, engine)

        City  Avg_Rating
0       Pune        4.40
1     Mumbai        4.40
2    Chennai        4.40
3      Delhi        4.40
4  Bengaluru        4.40
5  Hyderabad        4.39

In [38]:
query = """
SELECT
    City,
    ROUND(AVG(`Driver Rating`),2) AS Avg_Rating
FROM ola_rides
GROUP BY City
ORDER BY Avg_Rating DESC;
"""

pd.read_sql(query, engine)

        City  Avg_Rating
0    Chennai        4.51
1       Pune        4.50
2  Hyderabad        4.50
3      Delhi        4.50
4  Bengaluru        4.50
5     Mumbai        4.49

In [39]:
query = """
SELECT
    City,
    COUNT(*) AS Cancelled
FROM ola_rides
WHERE `Booking Status` <> 'Success'
GROUP BY City
ORDER BY Cancelled DESC;
"""

pd.read_sql(query, engine)

        City  Cancelled
0      Delhi       3398
1  Bengaluru       3356
2    Chennai       3340
3  Hyderabad       3329
4       Pune       3258
5     Mumbai       3180

In [40]:
query = """
SELECT
    `Payment Method`,
    COUNT(*) AS Total_Transactions
FROM ola_rides
GROUP BY `Payment Method`
ORDER BY Total_Transactions DESC;
"""

pd.read_sql(query, engine)

  Payment Method  Total_Transactions
0            UPI               49979
1           Cash               19972
2           Card               19904
3         Wallet               10145

In [41]:
query = """
SELECT
    `Pickup Location`,
    ROUND(SUM(`Booking Value`),2) AS Revenue
FROM ola_rides
GROUP BY `Pickup Location`
ORDER BY Revenue DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

   Pickup Location     Revenue
0      Indiranagar  1904180.45
1  Electronic City  1892455.27
2          MG Road  1880836.80
3          Airport  1873856.06
4           Hebbal  1869441.01
5       Whitefield  1860959.28
6        Yelahanka  1853832.34
7       HSR Layout  1834320.93
8      Koramangala  1830206.27
9     Marathahalli  1827578.55

In [42]:
query = """
SELECT
    `Drop Location`,
    ROUND(SUM(`Booking Value`),2) AS Revenue
FROM ola_rides
GROUP BY `Drop Location`
ORDER BY Revenue DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

     Drop Location     Revenue
0       HSR Layout  1899801.54
1           Hebbal  1877961.43
2      Koramangala  1877559.62
3        Yelahanka  1872199.23
4          MG Road  1866903.63
5       Whitefield  1864421.45
6          Airport  1854169.68
7     Marathahalli  1847753.10
8  Electronic City  1840891.17
9      Indiranagar  1826006.11

In [43]:
query = """
SELECT
    `Driver ID`,
    COUNT(*) AS Total_Rides,
    ROUND(AVG(`Driver Rating`),2) AS Avg_Rating
FROM ola_rides
GROUP BY `Driver ID`
ORDER BY Avg_Rating DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

  Driver ID  Total_Rides  Avg_Rating
0     D8712            2        5.30
1     D8196            5        5.25
2     D3717            4        5.23
3     D7952            4        5.12
4     D7577            5        5.10
5     D7881            9        5.10
6     D9136            7        5.05
7     D4014            4        5.05
8     D9111           10        5.04
9     D4623            7        5.03

In [44]:
query = """
SELECT
    `Customer ID`,
    COUNT(*) AS Total_Bookings
FROM ola_rides
GROUP BY `Customer ID`
ORDER BY Total_Bookings DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

  Customer ID  Total_Bookings
0      C82572               7
1      C84704               7
2      C31763               7
3      C48122               7
4      C39937               7
5      C43114               7
6      C17491               7
7      C82381               7
8      C48044               7
9      C57594               7

In [45]:
query = """
SELECT
    `Booking Category`,
    COUNT(*) AS Total_Rides
FROM ola_rides
GROUP BY `Booking Category`;
"""

pd.read_sql(query, engine)

  Booking Category  Total_Rides
0              Low        87671
1           Medium        12206
2             High          122
3          Premium            1

In [46]:
query = """
SELECT
    `Distance Category`,
    COUNT(*) AS Total_Rides,
    ROUND(AVG(`Booking Value`),2) AS Avg_Fare
FROM ola_rides
GROUP BY `Distance Category`;
"""

pd.read_sql(query, engine)

  Distance Category  Total_Rides  Avg_Fare
0              Long        28476    260.44
1             Short        29881     99.17
2            Medium        36300    163.82
3         Very Long         5343    430.69

In [47]:
query = """
SELECT
    Weather,
    ROUND(SUM(`Booking Value`),2) AS Revenue
FROM ola_rides
GROUP BY Weather;
"""

pd.read_sql(query, engine)

  Weather      Revenue
0   Rainy   3665291.88
1  Cloudy   3725083.67
2   Sunny  10293373.50
3     Fog    943917.91

In [48]:
query = """
SELECT
    Traffic,
    ROUND(AVG(`Ride Duration (min)`),2) AS Avg_Duration
FROM ola_rides
GROUP BY Traffic;
"""

pd.read_sql(query, engine)

  Traffic  Avg_Duration
0    High         47.89
1     Low         47.56
2  Medium         48.12

In [49]:
print("="*60)
print("40 SQL BUSINESS QUERIES COMPLETED")
print("="*60)
print("Notebook 5 Completed Successfully!")

============================================================
40 SQL BUSINESS QUERIES COMPLETED
============================================================
Notebook 5 Completed Successfully!